version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    depends_on:
      - db
    container_name: rails-groupen

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'
volumes:
  mysql-data:
