version: '3'
services:
  groupen:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - '3001:3001'
    depends_on:
      - groupen-mysql
  groupen-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3309:3309'
